FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN git clone https://github.com/upnodedev/upnode-deploy-ui.git .

ARG PROTOCOL
ARG DOMAIN_NAME

RUN echo "NEXT_PUBLIC_API_URL=${PROTOCOL}://deploy-api.${DOMAIN_NAME}/api" > .env

RUN npm install

ENV NODE_ENV production

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
