FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN git clone https://github.com/upnodedev/upnode-deploy-ui.git .

RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
