FROM traefik:v2.10

# Install envsubst
RUN apk add --no-cache gettext

# Copy the template file into the image
COPY dynamic.template.yml /etc/traefik/dynamic.template.yml

# Build the final dynamic.yml file during the image build
ARG DOMAIN_NAME
RUN envsubst '${DOMAIN_NAME}' < /etc/traefik/dynamic.template.yml > /etc/traefik/dynamic.yml

# Set the default command to run Traefik